# Generated by Django 4.2.1 on 2024-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
