# Generated by Django 4.2.1 on 2024-02-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0002_remove_contactinformation_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactinformation',
        ),
    ]
