# Generated by Django 4.2.1 on 2024-02-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0005_admissioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioninfo',
            name='sphoto',
            field=models.ImageField(upload_to='managementApp/images'),
        ),
    ]
