# Generated by Django 4.2.1 on 2024-03-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0007_remove_admissioninfo_sphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
    ]
