# Generated by Django 4.2.1 on 2024-03-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0011_alter_signupdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
