# Generated by Django 4.2.1 on 2024-03-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0012_alter_signupdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetails',
            name='mobileno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
