# Generated by Django 4.2.1 on 2024-03-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0015_alter_signupdetails_mobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetails',
            name='uname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
