# Generated by Django 4.2.1 on 2024-03-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0018_alter_signupdetails_uname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupdetails',
        ),
    ]
