# Generated by Django 4.2.1 on 2024-03-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0019_delete_signupdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.CharField(max_length=20)),
                ('unumber', models.CharField(max_length=11)),
                ('upassword', models.CharField(max_length=6)),
            ],
        ),
    ]
