# Generated by Django 4.2.1 on 2024-03-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0020_signupdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupdetails',
        ),
    ]
