# Generated by Django 4.2.1 on 2024-03-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0024_signupdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetail',
            name='uemail',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signupdetail',
            name='uname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signupdetail',
            name='unumber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='signupdetail',
            name='upassword',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
