# Generated by Django 4.2.1 on 2024-03-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0025_alter_signupdetail_uemail_alter_signupdetail_uname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupdetail',
        ),
    ]
