# Generated by Django 4.2.1 on 2024-03-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0027_userregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='uemail',
            new_name='remail',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='uname',
            new_name='rname',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='unumber',
            new_name='rnumber',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='upassword',
            new_name='rpassword',
        ),
    ]
