# Generated by Django 4.2.1 on 2024-03-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0028_rename_uemail_userregister_remail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userregister',
        ),
    ]
