# Generated by Django 4.2.1 on 2024-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0029_delete_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=20)),
                ('remail', models.CharField(max_length=20)),
                ('rnumber', models.CharField(max_length=11)),
                ('rpassword', models.CharField(max_length=6)),
            ],
        ),
    ]
